name: together_delivery_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  flutter_provider: ^2.1.0
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  go_router: ^13.2.2
  retrofit: ^4.1.0
  flutter_secure_storage: ^4.2.1
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  multi_image_picker_plus: ^0.0.4
  http_parser: ^4.0.2
  carousel_slider: ^5.0.0
  flutter_naver_map: ^1.2.3
  flutter_dotenv: ^5.1.0
  geolocator: ^11.0.0
  stomp_dart_client: ^2.0.0
  photo_view: ^0.15.0
  fluttertoast: ^8.2.4
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/config/.env
    - assets/lottie/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Black.ttf
          weight: 900
        - asset: assets/font/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Pretendard-Light.ttf
          weight: 300
        - asset: assets/font/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/font/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/font/Pretendard-Thin.ttf
          weight: 100
    - family: HancomMalangMalang
      fonts:
        - asset: assets/font/HancomMalangMalang-Regular.ttf